language: node_js
node_js:
 - "8"
 - "10"
 - "11"

cache: npm

git: depth: 3
before_install:
 - npm i -g @angular/cli
 
jobs:
  include:
    - stage: build
      script: ng build --prod --base-href="http://www.jtmorrisbytes.com/"
    - stage: test
      script: skip
