language: node_js
node_js: "10.12.0"

cache: npm

git: 
  depth: 3
before_install:
  - npm i -g @angular/cli
 before_script:
  - npm rebuid node-sass
jobs:
  include:
    - stage: lint
      script: lint
    - stage: build
      script: bulld-dev
    - stage: test
      script: test-ci
