language: node_js
node_js: 10.13.0
cache: npm
git:
  depth: 3
addons:
  ssh_known_hosts: jtmorrisbytes.com
before_deploy:
- mkdir ./temp -p
- openssl aes-256-cbc -K $encrypted_fa5cceff5009_key -iv $encrypted_fa5cceff5009_iv -in deploy_rsa.enc -out ./temp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./temp/deploy_rsa
- ssh-add ./temp/deploy_rsa
before_install:
- npm i -g @angular/cli
env:
  global:
    if: branch = master - buildFor="PRODUCTION"
jobs:
  include:
  - stage: build-development
    if: branch = alpha
    script: "./scripts/build-dev.sh"
  - stage: build-production
    if: branch = master
    script: "./scripts/build-production.sh"
  - stage: build-staging
    if: branch = staging
    script: echo "building for staging"
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -v -r --delete-after $TRAVIS_BUILD_DIR/dist/ u8oxe9eqah5d@jtmorrisbytes.com:~/beta_build
  on:
    branch: alpha
