language: node_js
node_js: 10.12.0
cache: npm
git:
  depth: 3
addons:
  ssh_known_hosts: jtmorrisbytes.com
before_deploy:
- openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
before_install:
- openssl aes-256-cbc -K $encrypted_f778b6d5ee91_key -iv $encrypted_f778b6d5ee91_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- npm i -g @angular/cli


deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist u8oxe9eqah5d@jtmorrisbytes.com:beta_build/
  on:
    branch: master
build:
  provider: script
  skip_cleanup: true
  script: ng build --base-href"http://www.jtmorrisbytes.com/" --output-path $TRAVIS_BUILD_DIR/dist
test:
  provider: script
  script: skip
