language: node_js
node_js: 10.13.0
cache: npm
git:
  depth: 5
addons:
  ssh_known_hosts: jtmorrisbytes.com
before_deploy:
- mkdir ./temp -p
before_install:
- npm i -g @angular/cli
jobs:
  include:
  - stage: test
    script: ng test --no-watch --browsers=ChromeHeadless
  - stage: build
    script: npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: VgbBU7JCDf9D6GSjHKx0+dfCcb9bfXkjpgvsCo994ZA1HCKa6zt9IDq6Lq+RynKDmqYC++TuDeEblR8zlzfkpAf6PZv2b8oGQBXKHgPfClvYTrfyXHCJmmlZX2U50s5HX0FQ0nmeo0rsQ1L3/jjTw0BDZkvrEbi2lS5qSUt9ZReS6M5iWLNTOGbjDtUooQp2IbzyY06xeHzgK+XvMYoaHVyAiPCIz++yH2a5NH7hsgFmywEkUA68XtIspu+wRWHYE43Yv/VV8EM/EH74lg8RZCqPut7ZTSfQ9WSiMHHlQSOV43r6fhZOs+Gck+FKPLBmGqJtUBvBYbS04mcGIKzjYP4MoHltJJOlsZGxhKURQI4m8CGLH8VQTL4rdoBX8AqgD3ZY6PY4zzVG2d5RTNd7fx0vv67nhekGwXSyyT/+GHU1Adt8R95za56qSHd6ppKeeDzzAB1wL2EzKIhXiqAoztotofxikkWnvbzTW71kdgMWyPuJSDEGuSVV3Zh3u3OUIFrIwjoAGsm+SvBAbI0foFusXrhvEkJjdRxv86LVTN4Sf8D3YQsH9mJiyam8zkHGHLccRFjGWTVNLU42pObIBgnS5fw+QO4u+pVUWzrEDOz4/tYnaqnU7+370grKs9P599frcIw78XrIv8YYy9KzuLlHhp8jnAQexdhuSnbvZxA=
  app:
    master: jtmorrisbytes
    staging: jtmorrisbytes-staging
    alpha: jtmorrisbytes-alpha
  on:
    all_branches: true
