language: node_js
node_js: 10.12.0
cache: npm
git:
  depth: 3
before_install:
- openssl aes-256-cbc -K $encrypted_f778b6d5ee91_key -iv $encrypted_f778b6d5ee91_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- npm i -g @angular/cli
jobs:
  include:
  - stage: build
    script: npm run build-dev
