language: node_js
node_js:
 - "8"
 - "10"
 - "11"

cache: npm

git:
 - depth: 3
before_install:
 - npm i -g @angular/cli
 
jobs:
  include:
    - stage: build
      script: ./scripts/build-dev.sh
    - stage: test
      script: ./scripts/test-dev.sh
