language: node_js
node_js: 10.13.0
cache: npm
git:
  depth: 5
addons:
  ssh_known_hosts: jtmorrisbytes.com
before_deploy:
- mkdir ./temp -p
before_install:
- npm i -g @angular/cli
jobs:
  include:
    stage: build
    script:
    - ng test --no-watch --browsers=ChromeHeadless
    - npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: aqzuM3Ilt9jfPev464hc/iUqIL0i3VnwJy4/1VDU5zwLNy3HHqj6V6+2F6tmMDJI8sq3SKB6WsQ7dyMGJ+C/SS2WQ5lRE3gNTRpVTe7OIzsMStZ3jJPllniN1uvaVtCHP+M2p0S30/aq0OSltCXnOLMXacKiVYRRIuC2F/K2P593WrNz9PvtRoIE5a36FBUpUZIn3OQg2OotkdTpAicUlI9N+QKBwQtkEgsZt3yT/gscga2AB1UQCMgz9M0Omn+/V45y2e0j2d/BuRg5OYlIkvT944PO7bttMhvXZYjVF866VtjzQIc6H2jr2cDdpS8Fruy0wd0B9hFbCWo+C+Fo9wohpdNqhs0nOEKSfW9R9xIEzLSUPoItTB0zEkwdTwi0h6JHhZD7OdDqNPzmmmBGp9uMPfZ4uajX3H4Ysoqjn3b0dtzNhhua/aiBI+/uG3ipzJYqesfWBqelsE1rWx9MleCqn30fP5mgrpoXt1ADmWg0INz5ME12wwUc/Hk6GULp+urMP3CWZuRUwzCyPw7PWteLJVHqK8GbXTcn+cXbJm5qyqZegJ7cE+g23ZVTyqRNKNo4lSub+XOtGlGRkjgap3hZCMJGMoWB+gx9PXaXFSkcZ01kOqzPine5KZF4/cZilrcFRTMxAq+fYZX3SnM8oHnhzN3jFraHrsBtAEafGAI=
  app:
    master: jtmorrisbytes
    staging: jtmorrisbytes-staging
    alpha: jtmorrisbytes-alpha
  on:
    all_branches: true
