[default]
proxy_proto_header=["X-Forwarded-Proto"]
port=443
address="::"
template_dir="app/templates"



[default.tls]
key="ssl/private_key.pem"
certs="ssl/certificate.pem"


[default.databases.primary]
url="postgres://postgres:postgres@localhost:5432/accounting_db"


[debug]
secret_key="6Zoa8SoaMlN++toh1BFO7rfEvAzon3KeX6szC+hUEhk="

[release]
secret_key="o7Dd2G8Grfn4mfRzArIbWst/R5mrQqAfWzOd9/aBm1U="