// may the gods have mercy on my soul....

// yes. we are importing our core crate requirements for our recursive build

#[path="src/core/mod.rs"]
mod core;


// yes we are pulling in the migrator code
#[path="src/migrator/mod.rs"]
mod migrator;


#[path="build/mod.rs"]
mod build;
// generated by `sqlx migrate build-script`
#[tokio::main]
async fn main() -> Result<(),Box<dyn std::error::Error>> {
    match dotenvy::dotenv() {
        Err(e)=>{
            println!("cargo:error={e}")
        },
        Ok(_)=>{}
    }
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=build");
    println!("cargo:rerun-if-changed=migrations");

    build::bring_up_db().await?;
    // trigger recompilation when a new migration is added
    // println!("cargo:rerun-if-changed=migrations");
    Ok(())
}
