[package]
name="sql"
version="0.1.0"
edition="2024"


[features]
sqlite=["barrel/sqlite3"]
postgresql=["barrel/pg"]
mysql=["barrel/mysql"]
default=["sqlite","postgresql","mysql"]
serialize=["serde"]
deserialize=["serde"]


[build-dependencies]
postgres-types = { version = "0.2", features = ["derive","with-uuid-1"] }
tokio-postgres = {version="^0.7.16",featues=["with-uuid-v1"]}
tokio = { version = "^1.50", features = ["rt-multi-thread","macros","net","fs"] }
rustls = "0.23.37"
webpki-roots = "1.0.6"
rustls-native-certs = "0.8.3"
deadpool = "=0.12.3"
deadpool-postgres = "=0.14.1"
tokio-postgres-rustls = "0.13.0"
uuid={version="1.7",features=["v7"]}
refinery = {version="0.9.0",features=['tokio-postgres']}
barrel = "0.7.0"
dotenvy = "0.15.7"

[dependencies]
#paste = "1.0.15"
#sqlx = {workspace=true, features=["migrate","uuid","sqlite"]}
uuid={version="1.7",features=["v7"]}
sql_proc_macro={path="../sql_proc_macros"}
anyhow = "1.0.102"
tokio = { version = "^1.50", features = ["full"] }
#dashmap = "6.1.0"
#async-trait = "0.1.89"
serde = { version = "1.0.228", features = ["derive"],optional=true }
barrel = "0.7.0"
refinery = {version="0.9.0",features=['tokio-postgres']}
postgres-types = { version = "0.2", features = ["derive","with-uuid-1"] }
tokio-postgres = {version="^0.7.16",featues=["with-uuid-v1"]}
deadpool = "=0.12.3"
#sea-query = { version = "0.32.7", features = ["backend-postgres","thread-safe"] }
rustls = "0.23.37"
tokio-postgres-rustls = "0.13.0"
webpki-roots = "1.0.6"
deadpool-postgres = "=0.14.1"
webpki = { version = "0.22.4", features = ["std"] }
rustls-native-certs = "0.8.3"
dotenvy = "0.15.7"
#sea-schema = { version = "0.16.2", default-features = false, features = ["def", "discovery", "futures", "parser", "postgres", "probe", "query", "writer"] }
#sea-query-postgres = "0.5.0"
