[package]
name="sql"
version="0.1.0"
edition="2024"


[features]
sqlite=["barrel/sqlite3"]
postgresql=["barrel/pg"]
mysql=["barrel/mysql"]
default=["sqlite","postgresql","mysql"]
serialize=["serde"]
deserialize=["serde"]


[dependencies]
paste = "1.0.15"
#sqlx = {workspace=true, features=["migrate","uuid","sqlite"]}
uuid={version="1.7",features=["v7"]}
sql_proc_macro={path="./accounting_proc_macro"}
anyhow = "1.0.102"
tokio = { version = "^1.50", features = ["full"] }
dashmap = "6.1.0"
async-trait = "0.1.89"
serde = { version = "1.0.228", features = ["derive"],optional=true }
barrel = "0.7.0"
refinery = "0.9.0"
tokio-postgres = "0.7.16"
deadpool = "0.13.0"
